# Generated by Django 2.2.11 on 2020-03-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncenter',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
