# Generated by Django 2.2.11 on 2020-03-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_order_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('description_detail', models.CharField(max_length=255)),
                ('image', models.CharField(default='', max_length=255)),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date_at',
            field=models.DateTimeField(),
        ),
    ]
